dist:
  name: otelcol-freebsd
  description: OpenTelemetry Collector for FreeBSD
  output_path: ./bin

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.91.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.91.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.91.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.91.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.91.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.91.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/ballastextension v0.91.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.91.0