# Copyright (c) 2024-2026 Bryan Everly
# Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
# See the LICENSE file in the project root for the full terms.

"""Who made the hardware behind a MAC address (Phase 21.6 S5).

Looked up in the IEEE registry table that ships WITH the server
(``backend/data/oui.tsv.gz``, regenerated by ``scripts/update_oui.py``), never
online: discovery must work on an air-gapped server, and a lookup service
would learn every device on every customer network.

Longest prefix wins: MA-S (36-bit) and MA-M (28-bit) blocks are carved out of
MA-L (24-bit) ones, and the smaller block names the actual maker.

A locally administered MAC has no vendor BY DEFINITION -- it was not assigned
by the IEEE (phones randomize them; hypervisors mint them) -- so it returns
None rather than whatever unrelated company holds the matching bits.
"""

import gzip
import logging
import os
import threading
from typing import Dict, Optional

logger = logging.getLogger(__name__)

PATH = os.path.join(os.path.dirname(__file__), "..", "data", "oui.tsv.gz")
_TABLE: Optional[Dict[str, str]] = None
_LOCK = threading.Lock()


def _load(path: str = PATH) -> Dict[str, str]:
    table: Dict[str, str] = {}
    try:
        with gzip.open(path, "rt", encoding="utf-8") as fh:
            for line in fh:
                if line.startswith("#") or "\t" not in line:
                    continue
                prefix, vendor = line.rstrip("\n").split("\t", 1)
                table[prefix] = vendor
    except OSError:
        # Loud: every device would silently show "unknown vendor" otherwise.
        logger.warning("MAC vendor table %s could not be read; vendors unknown", path)
    return table


def table() -> Dict[str, str]:
    global _TABLE  # pylint: disable=global-statement
    if _TABLE is None:
        with _LOCK:
            if _TABLE is None:
                _TABLE = _load()
    return _TABLE


def vendor_of(mac: Optional[str]) -> Optional[str]:
    """The registered maker for ``mac`` (any spelling), or None."""
    if not mac:
        return None
    hex_digits = "".join(c for c in mac.upper() if c in "0123456789ABCDEF")
    if len(hex_digits) != 12 or int(hex_digits[1], 16) & 0x2:
        return None  # malformed, or locally administered: no IEEE owner
    entries = table()
    for length in (9, 7, 6):
        vendor = entries.get(hex_digits[:length])
        if vendor:
            return vendor
    return None
