name: sysmanage
base: core22
version: git
summary: Centralized system management server with web-based interface
description: |
  SysManage is a comprehensive centralized system management server with a
  modern web-based interface. It provides:

  * Agent management and monitoring
  * System metrics and health monitoring
  * Comprehensive reporting system with PDF generation
  * JWT-based authentication with mTLS security
  * Multi-user management system with RBAC
  * Package inventory and updates
  * Certificate management
  * Real-time WebSocket communication
  * Cross-platform support (Linux, Windows, macOS, FreeBSD, OpenBSD)

  The server runs as a service and communicates with SysManage agents
  deployed across your infrastructure to provide centralized management.

license: AGPL-3.0
website: https://sysmanage.org
source-code: https://github.com/bceverly/sysmanage
issues: https://github.com/bceverly/sysmanage/issues
contact: https://github.com/bceverly/sysmanage/issues

icon: snap/gui/icon.svg

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  sysmanage:
    command: bin/sysmanage-wrapper
    daemon: simple
    restart-condition: always
    restart-delay: 10s
    plugs:
      - network
      - network-bind

parts:
  python310:
    plugin: nil
    source: https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tgz
    source-checksum: sha256/a27864e5ba2a4474f8f6c58ab92ff52767ac8b66f1646923355a53fe3ef15074
    build-attributes:
      - enable-patchelf
    build-packages:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libgdbm-dev
      - libdb-dev
      - libbz2-dev
      - libexpat1-dev
      - liblzma-dev
      - libffi-dev
      - uuid-dev
      - wget
    override-build: |
      ./configure --prefix=/usr --enable-optimizations --enable-shared LDFLAGS="-Wl,-rpath,/usr/lib"
      make -j$(nproc)
      make DESTDIR=$CRAFT_PART_INSTALL install
      # Ensure shared libraries can be found
      ldconfig -n $CRAFT_PART_INSTALL/usr/lib || true

  backend:
    after: [python310]
    plugin: nil
    build-packages:
      - libpq-dev
      - gcc
      - g++
      - libffi-dev
      - libssl-dev
      - rsync
    override-build: |
      # $CRAFT_PROJECT_DIR is the project root when running snapcraft from root with path to snapcraft.yaml
      # Create temp build directory
      mkdir -p /tmp/build

      # Copy only the files and directories we need using cp with exclusions
      cp "$CRAFT_PROJECT_DIR/requirements.txt" /tmp/build/
      cp -r "$CRAFT_PROJECT_DIR/scripts" /tmp/build/
      cp -r "$CRAFT_PROJECT_DIR/backend" /tmp/build/
      cp -r "$CRAFT_PROJECT_DIR/alembic" /tmp/build/
      cp "$CRAFT_PROJECT_DIR/alembic.ini" /tmp/build/
      cp -r "$CRAFT_PROJECT_DIR/config" /tmp/build/

      # Copy requirements-prod.txt if it exists
      if [ -f "$CRAFT_PROJECT_DIR/requirements-prod.txt" ]; then
        cp "$CRAFT_PROJECT_DIR/requirements-prod.txt" /tmp/build/
      fi

      # Generate requirements-prod.txt if it doesn't exist
      if [ ! -f "/tmp/build/requirements-prod.txt" ]; then
        cd /tmp/build
        python3 scripts/update-requirements-prod.py
      fi

      # Install Python packages using our compiled Python 3.10
      export LD_LIBRARY_PATH=$CRAFT_STAGE/usr/lib:${LD_LIBRARY_PATH:-}
      export PYTHONHASHSEED=0
      $CRAFT_STAGE/usr/bin/python3.10 -m pip install --no-cache-dir --target=$CRAFT_PART_INSTALL/lib/python3.10/site-packages \
        -r /tmp/build/requirements-prod.txt

      # Copy application files
      mkdir -p $CRAFT_PART_INSTALL/app
      cp -r /tmp/build/backend $CRAFT_PART_INSTALL/app/
      cp -r /tmp/build/alembic $CRAFT_PART_INSTALL/app/
      cp /tmp/build/alembic.ini $CRAFT_PART_INSTALL/app/
      cp -r /tmp/build/config $CRAFT_PART_INSTALL/app/
      cp -r /tmp/build/scripts $CRAFT_PART_INSTALL/app/

  frontend:
    plugin: nil
    build-attributes:
      - enable-patchelf
    build-packages:
      - curl
      - ca-certificates
      - gnupg
      - rsync
    override-build: |
      # $CRAFT_PROJECT_DIR is the project root when running snapcraft from root with path to snapcraft.yaml
      # Create temp build directory
      mkdir -p /tmp/build-frontend

      # Copy the frontend directory (excluding node_modules and dist which will be rebuilt)
      cp -r "$CRAFT_PROJECT_DIR/frontend/"* /tmp/build-frontend/

      # Install Node.js 20 LTS from NodeSource
      curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      apt-get install -y nodejs

      # Build frontend
      cd /tmp/build-frontend
      npm install --legacy-peer-deps
      npm run build
      mkdir -p $CRAFT_PART_INSTALL/app/frontend
      cp -r dist $CRAFT_PART_INSTALL/app/frontend/
      cp -r public $CRAFT_PART_INSTALL/app/frontend/

  wrapper:
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat > $CRAFT_PART_INSTALL/bin/sysmanage-wrapper <<'EOF'
      #!/bin/bash
      set -e

      # Set up environment using snap-specific paths
      # $SNAP_DATA: writable per-revision data (/var/snap/sysmanage/current)
      # $SNAP_COMMON: writable common data (/var/snap/sysmanage/common)
      export SYSMANAGE_CONFIG_PATH="${SYSMANAGE_CONFIG_PATH:-$SNAP_DATA/sysmanage.yaml}"
      export SYSMANAGE_CERT_PATH="${SYSMANAGE_CERT_PATH:-$SNAP_DATA/certs}"
      export SYSMANAGE_LOG_DIR="${SYSMANAGE_LOG_DIR:-$SNAP_COMMON/logs}"
      export PYTHONPATH="$SNAP/app:$SNAP/lib/python3.10/site-packages"
      export LD_LIBRARY_PATH="$SNAP/usr/lib:$LD_LIBRARY_PATH"

      # Ensure directories exist
      mkdir -p "$SYSMANAGE_CERT_PATH"
      mkdir -p "$SYSMANAGE_LOG_DIR"

      # Check for config file, copy example if missing
      if [ ! -f "$SYSMANAGE_CONFIG_PATH" ]; then
        echo "Configuration file not found at $SYSMANAGE_CONFIG_PATH"
        echo "Creating from example template..."
        cp "$SNAP/app/config/sysmanage.yaml.example" "$SYSMANAGE_CONFIG_PATH"
        echo ""
        echo "IMPORTANT: You must edit the configuration file before starting:"
        echo "  $SYSMANAGE_CONFIG_PATH"
        echo ""
        echo "At minimum, configure:"
        echo "  - Database connection settings"
        echo "  - JWT secret key"
        echo "  - TLS certificates"
        echo ""
        exit 1
      fi

      # Start the application
      cd $SNAP/app
      exec $SNAP/usr/bin/python3.10 -m backend.main
      EOF
      chmod +x $CRAFT_PART_INSTALL/bin/sysmanage-wrapper
