"""Add user locking fields to model

Revision ID: 3196f6f22b62
Revises: a1dd3bcc9546
Create Date: 2025-08-28 08:14:04.255960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3196f6f22b62'
down_revision: Union[str, None] = 'a1dd3bcc9546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with defaults for existing data
    op.add_column('user', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('locked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locked_at')
    op.drop_column('user', 'failed_login_attempts')
    op.drop_column('user', 'is_locked')
    # ### end Alembic commands ###
