"""Add secrets metadata table

Revision ID: 392b0f4105cf
Revises: 904046eab30e
Create Date: 2025-09-23 19:49:33.387363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392b0f4105cf'
down_revision: Union[str, None] = '904046eab30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secrets',
        sa.Column('id', sa.UUID(), primary_key=True, nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('secret_type', sa.String(50), nullable=False),
        sa.Column('key_visibility', sa.String(20), nullable=True),  # For SSH keys: 'public' or 'private'
        sa.Column('vault_token', sa.Text(), nullable=False),  # Token to retrieve secret from OpenBAO
        sa.Column('vault_path', sa.String(500), nullable=False),  # Path in vault where secret is stored
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.String(255), nullable=False),  # Username who created the secret
        sa.Column('updated_by', sa.String(255), nullable=False)   # Username who last updated the secret
    )

    # Create indexes for performance
    op.create_index('ix_secrets_name', 'secrets', ['name'])
    op.create_index('ix_secrets_secret_type', 'secrets', ['secret_type'])
    op.create_index('ix_secrets_created_at', 'secrets', ['created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_secrets_created_at')
    op.drop_index('ix_secrets_secret_type')
    op.drop_index('ix_secrets_name')
    op.drop_table('secrets')
    # ### end Alembic commands ###
