"""Add secure host_token column

Revision ID: 3cc63cc81f0c
Revises: 78d8552b0378
Create Date: 2025-09-17 16:34:09.718556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc63cc81f0c'
down_revision: Union[str, None] = '78d8552b0378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('host_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_host_host_token'), 'host', ['host_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_host_token'), table_name='host')
    op.drop_column('host', 'host_token')
    # ### end Alembic commands ###
