"""add enabled_shells column to host table

Revision ID: 3dcb1e896d05
Revises: 9c4f5ed7eb14
Create Date: 2025-09-12 06:55:17.682432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dcb1e896d05'
down_revision: Union[str, None] = '9c4f5ed7eb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
