"""add enabled_shells column to host table for real

Revision ID: 5cf4689c3227
Revises: 3dcb1e896d05
Create Date: 2025-09-12 06:55:53.801284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf4689c3227'
down_revision: Union[str, None] = '3dcb1e896d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('enabled_shells', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'enabled_shells')
    # ### end Alembic commands ###
