"""add_filename_to_secrets

Revision ID: 5e42e12dc12d
Revises: 7c457810ab35
Create Date: 2025-09-24 12:33:23.213706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e42e12dc12d'
down_revision: Union[str, None] = '7c457810ab35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secrets', 'filename')
    # ### end Alembic commands ###
