"""add_filename_to_secrets

Revision ID: 5e42e12dc12d
Revises: 7c457810ab35
Create Date: 2025-09-24 12:33:23.213706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e42e12dc12d'
down_revision: Union[str, None] = '7c457810ab35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the filename column already exists before adding it
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if inspector.has_table('secrets'):
        columns = inspector.get_columns('secrets')
        column_names = [col['name'] for col in columns]

        if 'filename' not in column_names:
            # Column doesn't exist, add it
            op.add_column('secrets', sa.Column('filename', sa.String(length=255), nullable=True))
        # If filename already exists, do nothing (already migrated)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the filename column exists before dropping it
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if inspector.has_table('secrets'):
        columns = inspector.get_columns('secrets')
        column_names = [col['name'] for col in columns]

        if 'filename' in column_names:
            # Column exists, drop it
            op.drop_column('secrets', 'filename')
    # ### end Alembic commands ###
