"""add_operation_type_to_installation_requests

Revision ID: 7143f0c46db0
Revises: d6cc20a06607
Create Date: 2025-09-20 20:34:29.989735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7143f0c46db0'
down_revision: Union[str, None] = 'd6cc20a06607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists (for test environments)
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Check if table exists first
    existing_tables = inspector.get_table_names()
    if 'installation_requests' not in existing_tables:
        # Table doesn't exist yet, skip this migration
        return

    columns = [col['name'] for col in inspector.get_columns('installation_requests')]

    if 'operation_type' not in columns:
        # Add operation_type column to installation_requests table
        op.add_column('installation_requests', sa.Column('operation_type', sa.String(length=20), server_default='install', nullable=False))
        op.create_index('ix_installation_requests_operation_type', 'installation_requests', ['operation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove operation_type column from installation_requests table
    op.drop_index('ix_installation_requests_operation_type', table_name='installation_requests')
    op.drop_column('installation_requests', 'operation_type')
    # ### end Alembic commands ###
