"""add ubuntu pro master key settings table

Revision ID: 78d8552b0378
Revises: af16fb874b63
Create Date: 2025-09-16 11:46:34.840489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d8552b0378'
down_revision: Union[str, None] = 'af16fb874b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ubuntu_pro_settings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('master_key', sa.Text(), nullable=True),
        sa.Column('organization_name', sa.String(length=255), nullable=True),
        sa.Column('auto_attach_enabled', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # Insert default row since this is a singleton settings table
    op.execute("""
        INSERT INTO ubuntu_pro_settings (id, auto_attach_enabled, created_at, updated_at)
        VALUES (1, FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubuntu_pro_settings')
    # ### end Alembic commands ###
