"""Add script_execution_enabled column to host table

Revision ID: 9c4f5ed7eb14
Revises: 63b0253b9c9c
Create Date: 2025-09-11 17:08:13.364205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4f5ed7eb14'
down_revision: Union[str, None] = '63b0253b9c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('script_execution_enabled', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_host_tags_host_id'), table_name='host_tags')
    op.drop_index(op.f('ix_host_tags_tag_id'), table_name='host_tags')
    op.drop_constraint(op.f('tags_name_key'), 'tags', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tags_name_key'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_host_tags_tag_id'), 'host_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_host_tags_host_id'), 'host_tags', ['host_id'], unique=False)
    op.drop_column('host', 'script_execution_enabled')
    # ### end Alembic commands ###
