"""Add diagnostics request tracking to host table

Revision ID: a85c2843f5c0
Revises: 6797b62e3500
Create Date: 2025-09-09 15:09:53.343840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85c2843f5c0'
down_revision: Union[str, None] = '6797b62e3500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('diagnostics_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('host', sa.Column('diagnostics_request_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'diagnostics_request_status')
    op.drop_column('host', 'diagnostics_requested_at')
    # ### end Alembic commands ###
