"""Add software_updated_at to host table

Revision ID: b8fdbd25e034
Revises: f0160fd810f2
Create Date: 2025-09-01 11:13:02.997266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fdbd25e034'
down_revision: Union[str, None] = 'f0160fd810f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('software_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'software_updated_at')
    # ### end Alembic commands ###
