"""Add profile image fields to user table

Revision ID: dc5ef218e166
Revises: a85c2843f5c0
Create Date: 2025-09-10 07:28:21.142767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5ef218e166'
down_revision: Union[str, None] = 'a85c2843f5c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.LargeBinary(), nullable=True))
    op.add_column('user', sa.Column('profile_image_type', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('profile_image_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image_uploaded_at')
    op.drop_column('user', 'profile_image_type')
    op.drop_column('user', 'profile_image')
    # ### end Alembic commands ###
