"""Added table to track issued tokens for deny listing

Revision ID: e429468a47ed
Revises: 363c803d1154
Create Date: 2024-05-13 08:45:23.953731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e429468a47ed'
down_revision: Union[str, None] = '363c803d1154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bearer_token',
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_bearer_token_token'), 'bearer_token', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bearer_token_token'), table_name='bearer_token')
    op.drop_table('bearer_token')
    # ### end Alembic commands ###
