"""Create software_packages table

Revision ID: f0160fd810f2
Revises: 45146a9ce1c8
Create Date: 2025-09-01 10:35:12.720933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0160fd810f2'
down_revision: Union[str, None] = '45146a9ce1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('package_manager', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('install_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('license_type', sa.String(length=100), nullable=True),
    sa.Column('bundle_id', sa.String(length=255), nullable=True),
    sa.Column('app_store_id', sa.String(length=50), nullable=True),
    sa.Column('installation_path', sa.String(length=500), nullable=True),
    sa.Column('is_system_package', sa.Boolean(), nullable=False),
    sa.Column('is_user_installed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('software_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_packages_package_manager'), 'software_packages', ['package_manager'], unique=False)
    op.create_index(op.f('ix_software_packages_package_name'), 'software_packages', ['package_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_software_packages_package_name'), table_name='software_packages')
    op.drop_index(op.f('ix_software_packages_package_manager'), table_name='software_packages')
    op.drop_table('software_packages')
    # ### end Alembic commands ###
