"""add_host_roles_table

Revision ID: f02c3958456f
Revises: 8a0423f9a92f
Create Date: 2025-09-28 15:43:04.114408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.persistence.models.core import GUID


# revision identifiers, used by Alembic.
revision: str = 'f02c3958456f'
down_revision: Union[str, None] = '8a0423f9a92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', GUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('package_version', sa.String(length=100), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('service_status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('diagnostic_report_collection_id_key'), 'diagnostic_report', type_='unique')
    op.drop_index(op.f('ix_diagnostic_report_collection_id'), table_name='diagnostic_report')
    op.create_index(op.f('ix_diagnostic_report_collection_id'), 'diagnostic_report', ['collection_id'], unique=True)
    op.drop_constraint(op.f('password_reset_token_token_key'), 'password_reset_token', type_='unique')
    op.drop_index(op.f('ix_password_reset_token_token'), table_name='password_reset_token')
    op.create_index(op.f('ix_password_reset_token_token'), 'password_reset_token', ['token'], unique=True)
    op.drop_constraint(op.f('script_execution_log_execution_id_key'), 'script_execution_log', type_='unique')
    op.drop_constraint(op.f('script_execution_log_execution_uuid_key'), 'script_execution_log', type_='unique')
    op.drop_index(op.f('ix_script_execution_log_execution_id'), table_name='script_execution_log')
    op.create_index(op.f('ix_script_execution_log_execution_id'), 'script_execution_log', ['execution_id'], unique=True)
    op.drop_index(op.f('ix_script_execution_log_execution_uuid'), table_name='script_execution_log')
    op.create_index(op.f('ix_script_execution_log_execution_uuid'), 'script_execution_log', ['execution_uuid'], unique=True)
    op.drop_constraint(op.f('software_installation_log_installation_id_key'), 'software_installation_log', type_='unique')
    op.drop_index(op.f('ix_software_installation_log_installation_id'), table_name='software_installation_log')
    op.create_index(op.f('ix_software_installation_log_installation_id'), 'software_installation_log', ['installation_id'], unique=True)
    op.drop_constraint(op.f('tags_name_key'), 'tags', type_='unique')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.drop_constraint(op.f('user_userid_key'), 'user', type_='unique')
    op.drop_index(op.f('ix_user_userid'), table_name='user')
    op.create_index(op.f('ix_user_userid'), 'user', ['userid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_userid'), table_name='user')
    op.create_index(op.f('ix_user_userid'), 'user', ['userid'], unique=False)
    op.create_unique_constraint(op.f('user_userid_key'), 'user', ['userid'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_unique_constraint(op.f('tags_name_key'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_software_installation_log_installation_id'), table_name='software_installation_log')
    op.create_index(op.f('ix_software_installation_log_installation_id'), 'software_installation_log', ['installation_id'], unique=False)
    op.create_unique_constraint(op.f('software_installation_log_installation_id_key'), 'software_installation_log', ['installation_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_script_execution_log_execution_uuid'), table_name='script_execution_log')
    op.create_index(op.f('ix_script_execution_log_execution_uuid'), 'script_execution_log', ['execution_uuid'], unique=False)
    op.drop_index(op.f('ix_script_execution_log_execution_id'), table_name='script_execution_log')
    op.create_index(op.f('ix_script_execution_log_execution_id'), 'script_execution_log', ['execution_id'], unique=False)
    op.create_unique_constraint(op.f('script_execution_log_execution_uuid_key'), 'script_execution_log', ['execution_uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('script_execution_log_execution_id_key'), 'script_execution_log', ['execution_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_password_reset_token_token'), table_name='password_reset_token')
    op.create_index(op.f('ix_password_reset_token_token'), 'password_reset_token', ['token'], unique=False)
    op.create_unique_constraint(op.f('password_reset_token_token_key'), 'password_reset_token', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_diagnostic_report_collection_id'), table_name='diagnostic_report')
    op.create_index(op.f('ix_diagnostic_report_collection_id'), 'diagnostic_report', ['collection_id'], unique=False)
    op.create_unique_constraint(op.f('diagnostic_report_collection_id_key'), 'diagnostic_report', ['collection_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('host_roles')
    # ### end Alembic commands ###
