"""
Air-gap install bundles.

Tracks ISO images generated by the multi-OS bundle builder (kicked off
from the "Air-Gap Bundles" tab in Settings).  Each row corresponds to
one ISO sitting on disk — typically under
``/var/lib/sysmanage/airgap-bundles/``.

The actual bundle build is done by a subprocess that runs
``scripts/buildAirGapBundle.sh server|agent``.  The build is *slow*
(Docker containers per Linux distro, pip wheel compilation, ISO
generation) so it runs asynchronously and updates this row's
``status`` as it progresses.

States:
    queued     -> build hasn't started yet
    building   -> subprocess is running, see ``log_path``
    ready      -> ISO is on disk at ``file_path``, available for download
    failed     -> subprocess exited non-zero; ``error_message`` summarizes
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Text

from backend.persistence.db import Base
from backend.persistence.models.core import GUID

# Product the bundle targets.  Two values today; nothing stopping us from
# adding more later (e.g. "scanner" once that surfaces).
BUNDLE_PRODUCT_SERVER = "server"
BUNDLE_PRODUCT_AGENT = "agent"
BUNDLE_PRODUCTS = (BUNDLE_PRODUCT_SERVER, BUNDLE_PRODUCT_AGENT)

# Lifecycle states.
BUNDLE_STATUS_QUEUED = "queued"
BUNDLE_STATUS_BUILDING = "building"
BUNDLE_STATUS_READY = "ready"
BUNDLE_STATUS_FAILED = "failed"
BUNDLE_STATUSES = (
    BUNDLE_STATUS_QUEUED,
    BUNDLE_STATUS_BUILDING,
    BUNDLE_STATUS_READY,
    BUNDLE_STATUS_FAILED,
)


class AirGapBundle(Base):
    """One multi-OS air-gap install ISO build job + its on-disk artifact."""

    __tablename__ = "airgap_bundle"

    id = Column(GUID(), primary_key=True, default=uuid.uuid4)
    product = Column(String(16), nullable=False, index=True)  # BUNDLE_PRODUCTS
    status = Column(
        String(16), nullable=False, index=True, default=BUNDLE_STATUS_QUEUED
    )

    created_at = Column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(timezone.utc).replace(tzinfo=None),
    )
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)

    # Set when status transitions to "ready".  Absolute path on the
    # sysmanage server's filesystem; the API serves the file from here
    # via streaming response.
    file_path = Column(Text, nullable=True)
    size_bytes = Column(Integer, nullable=True)

    # Path to the build log on disk (kept whether the build succeeded
    # or failed — useful for debugging failed builds).
    log_path = Column(Text, nullable=True)

    # Populated when status transitions to "failed".  First line of
    # subprocess stderr, truncated.
    error_message = Column(Text, nullable=True)

    # The user who triggered the build.  Nullable because the recovery
    # config-admin account has no DB row (and is allowed to trigger
    # bundles for bootstrap scenarios).
    created_by_user_id = Column(
        GUID(), ForeignKey("user.id", ondelete="SET NULL"), nullable=True
    )
