# Copyright (c) 2024-2026 Bryan Everly
# Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
# See the LICENSE file in the project root for the full terms.

"""Verify the authenticity of a Pro+ module bundle before it is loaded.

WHAT THIS REPLACES
------------------
``ModuleLoader`` used to trust an ``X-Content-SHA512`` response header — the
hash arrived in the SAME response as the payload it vouched for, so anyone who
could serve that response supplied both.  It also read

    if expected_hash and actual != expected:

meaning an ABSENT header skipped verification altogether: an attacker needed
only to omit it.  And nothing verified the cache path at all — once an engine
was on disk, it was loaded unconditionally on every subsequent start.

These are native shared objects loaded into the server process, so that was a
remote-code-execution path dressed as an integrity check.

WHAT IT DOES INSTEAD
--------------------
Every bundle produced by the Pro+ build carries ``MANIFEST.json`` (identity +
sha256 of each file) and ``MANIFEST.sig`` (Ed25519 over the manifest's exact
bytes).  Verification is:

  1. signature over MANIFEST.json validates against a key compiled in HERE
  2. the manifest's identity matches the module actually being loaded
  3. every file listed still hashes to what the manifest says
  4. the .so about to be loaded is one of those files

Failing ANY of these means the module does not load.  There is no
"continue with a warning" path and no environment variable to disable it: an
integrity control that can be switched off by whoever is trying to defeat it
is decoration.  Locally built engines are signed by the same key
(``scripts/package_bundles.py`` in the Pro+ repo refuses to build unsigned),
so development does not need an exemption.

TRUST ANCHOR
------------
``_TRUSTED_KEYS`` is compiled into the server deliberately.  Reading the key
from a file beside the modules would mean an attacker who can replace a
module can replace the key that vouches for it — the check would verify only
that the attacker is self-consistent.  Rotation therefore ships as a server
release; the list holds more than one key so a rotation can overlap.
"""

import base64
import hashlib
import json
import logging
import os
from typing import List, Optional, Tuple

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

logger = logging.getLogger(__name__)

MANIFEST_NAME = "MANIFEST.json"
SIGNATURE_NAME = "MANIFEST.sig"

# Raw Ed25519 public keys, base64.  Generated by the Pro+ repo's
# scripts/gen_module_signing_key.py.  Multiple entries are allowed ONLY to make
# key rotation overlap possible; drop the retired key in the release after the
# rotation completes.
#
# An empty list means nothing can be verified, so nothing loads.  That is the
# correct failure direction: a build that forgot its trust anchor must not
# silently accept unsigned code.
_TRUSTED_KEYS: List[str] = [
    # SysManage module signing key (2026-08).
    "CZrf8CRZPtwCPgdRZZxMoki/qKv1nKbFBrSQ7+kzBNw=",
]


# Plugin bundles are a bare ``<code>-plugin.iife.js``, served from a license
# server API endpoint rather than as a static file — so unlike an engine there
# is no container to carry a signature, and no second URL to fetch one from
# without changing the license server.  The signature therefore travels INSIDE
# the file, as a trailing JS line comment: the bundle stays a valid script,
# the existing endpoint is unchanged, and the signature survives being cached
# to disk so it can be re-checked on every use rather than only at download.
PLUGIN_SIG_PREFIX = "//# sysmanage-signature: "


class ModuleSignatureError(Exception):
    """A bundle failed authenticity verification and must not be loaded."""


def _trusted_public_keys() -> List[Ed25519PublicKey]:
    keys = []
    for encoded in _TRUSTED_KEYS:
        try:
            raw = base64.b64decode(encoded, validate=True)
            if len(raw) != 32:
                raise ValueError(f"expected 32 raw bytes, got {len(raw)}")
            keys.append(Ed25519PublicKey.from_public_bytes(raw))
        except Exception as exc:  # noqa: BLE001
            # A malformed anchor is a build error, not a runtime condition.
            # Log and skip rather than raising: one bad entry must not disable
            # a good one sitting next to it during a rotation.
            logger.error(
                "Ignoring unusable module signing key %r: %s", encoded[:12], exc
            )
    return keys


def _sha256_file(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _read_manifest(module_dir: str) -> Tuple[bytes, bytes]:
    manifest_path = os.path.join(module_dir, MANIFEST_NAME)
    signature_path = os.path.join(module_dir, SIGNATURE_NAME)
    for path in (manifest_path, signature_path):
        if not os.path.isfile(path):
            raise ModuleSignatureError(
                f"unsigned module: {os.path.basename(path)} missing from "
                f"{module_dir}. Re-download it; bundles published before module "
                f"signing are not loadable."
            )
    with open(manifest_path, "rb") as handle:
        manifest = handle.read()
    with open(signature_path, "rb") as handle:
        signature = handle.read().strip()
    return manifest, signature


def _verify_signature(manifest: bytes, signature_b64: bytes) -> None:
    keys = _trusted_public_keys()
    if not keys:
        raise ModuleSignatureError(
            "no usable module signing key is compiled into this build - "
            "refusing to load native code that cannot be verified"
        )
    try:
        signature = base64.b64decode(signature_b64, validate=True)
    except Exception as exc:  # noqa: BLE001
        raise ModuleSignatureError(f"malformed signature: {exc}") from exc
    for key in keys:
        try:
            key.verify(signature, manifest)
            return
        except InvalidSignature:
            continue
    raise ModuleSignatureError(
        "signature does not verify against any trusted module signing key"
    )


def verify_module_dir(
    module_dir: str,
    module_code: str,
    so_path: str,
    platform_info: Optional[dict] = None,
) -> None:
    """Raise ``ModuleSignatureError`` unless ``so_path`` is authentic.

    ``platform_info`` is the loader's own ``{platform, architecture,
    python_version}``.  Checking it matters: without it a correctly signed
    bundle built for another platform — or a signed OLD version replayed over
    a patched one — would verify happily.
    """
    manifest_bytes, signature = _read_manifest(module_dir)
    _verify_signature(manifest_bytes, signature)

    try:
        manifest = json.loads(manifest_bytes)
    except json.JSONDecodeError as exc:
        raise ModuleSignatureError(f"manifest is not valid JSON: {exc}") from exc

    if manifest.get("module_code") != module_code:
        raise ModuleSignatureError(
            f"manifest is for {manifest.get('module_code')!r}, not "
            f"{module_code!r} - a signed bundle for a different engine"
        )
    if platform_info:
        for field in ("platform", "architecture"):
            want = platform_info.get(field)
            got = manifest.get(field)
            if want and got and want != got:
                raise ModuleSignatureError(
                    f"manifest {field} is {got!r}, this host needs {want!r}"
                )
        # python_version is NOT a plain equality check.  Engines build once
        # under the limited API and are stored as ``abi3``, while
        # ``_get_platform_info`` reports the running interpreter ("3.14") --
        # comparing the two directly rejected every genuine bundle, which is
        # how this nearly shipped as a total Pro+ outage rather than a
        # security fix.  ``abi3`` is deliberately compatible with any
        # supported CPython; anything else must match exactly.
        want_py = platform_info.get("python_version")
        got_py = manifest.get("python_version")
        if want_py and got_py and got_py != "abi3" and want_py != got_py:
            raise ModuleSignatureError(
                f"manifest python_version is {got_py!r}, this host needs "
                f"{want_py!r}"
            )

    files = manifest.get("files") or {}
    if not isinstance(files, dict) or not files:
        raise ModuleSignatureError("manifest lists no files")

    # Every listed file must still match.  Checking only the .so would leave
    # the gettext catalogs unverified, and those are read by the engine.
    for arcname, expected in sorted(files.items()):
        target = os.path.join(module_dir, arcname)
        if not os.path.isfile(target):
            raise ModuleSignatureError(f"manifest lists {arcname}, which is missing")
        actual = _sha256_file(target)
        if actual != expected:
            raise ModuleSignatureError(
                f"{arcname} does not match the signed manifest "
                f"(expected {expected[:16]}..., got {actual[:16]}...)"
            )

    # The file we are about to dlopen must be one the manifest covers -- not
    # merely sitting in a directory where other files happen to verify.
    so_name = os.path.relpath(os.path.realpath(so_path), os.path.realpath(module_dir))
    if so_name not in files:
        raise ModuleSignatureError(f"{so_name} is not covered by the signed manifest")

    # ...and NOTHING ELSE may be in the directory.  Checking only the listed
    # files left an attacker free to drop an extra .so alongside them: every
    # manifest entry still verified, so the directory passed.  Nothing loads
    # that file today -- the path comes from the cache row or from the single
    # compiled file found at extraction -- but "the manifest describes this
    # directory" has to mean the whole directory, or the next change to how a
    # module path is chosen silently reopens it.  Found by the adversarial
    # test, not by design.
    unexpected = []
    real_dir = os.path.realpath(module_dir)
    for root, _dirs, names in os.walk(real_dir):
        for name in names:
            rel = os.path.relpath(os.path.join(root, name), real_dir)
            if rel in (MANIFEST_NAME, SIGNATURE_NAME) or rel in files:
                continue
            unexpected.append(rel)
    if unexpected:
        raise ModuleSignatureError(
            "directory holds file(s) the signed manifest does not cover: "
            + ", ".join(sorted(unexpected)[:5])
        )


def verify_plugin_bundle(path: str, module_code: str) -> None:
    """Raise ``ModuleSignatureError`` unless the plugin bundle is authentic.

    The bundle is JS executed in an authenticated administrator's browser, so
    a substituted one is script execution in that session -- the same severity
    class as a substituted engine, reached through a different door.  It was
    protected by the same ``X-Content-SHA512`` header the engines used, with
    the same fail-open ``if expected_hash:`` and the same absence of any check
    on the cache path.

    Format: the last line is ``//# sysmanage-signature: <base64 JSON>`` where
    the JSON is ``{"manifest": <canonical string>, "sig": <base64>}``.  The
    signature covers the manifest, and the manifest carries the sha256 of
    everything preceding the trailer -- so the body cannot change without
    invalidating it, and the manifest binds the module identity so one signed
    plugin cannot be served in place of another.
    """
    try:
        with open(path, "rb") as handle:
            raw = handle.read()
    except OSError as exc:
        raise ModuleSignatureError(f"cannot read plugin bundle: {exc}") from exc

    marker = PLUGIN_SIG_PREFIX.encode("ascii")
    index = raw.rfind(b"\n" + marker)
    if index < 0:
        raise ModuleSignatureError(
            f"unsigned plugin bundle for {module_code}: no signature trailer. "
            "Bundles published before plugin signing are not loadable; "
            "re-download it."
        )

    body = raw[:index]
    trailer = raw[index + 1 + len(marker) :].strip()
    try:
        envelope = json.loads(base64.b64decode(trailer, validate=True))
        manifest_bytes = envelope["manifest"].encode("utf-8")
        signature = envelope["sig"].encode("ascii")
    except Exception as exc:  # noqa: BLE001
        raise ModuleSignatureError(f"malformed plugin signature: {exc}") from exc

    _verify_signature(manifest_bytes, signature)

    manifest = json.loads(manifest_bytes)
    if manifest.get("module_code") != module_code:
        raise ModuleSignatureError(
            f"plugin manifest is for {manifest.get('module_code')!r}, not "
            f"{module_code!r} - a signed plugin for a different engine"
        )
    expected = manifest.get("sha256")
    actual = hashlib.sha256(body).hexdigest()
    if actual != expected:
        raise ModuleSignatureError(
            f"plugin body does not match its signed manifest "
            f"(expected {str(expected)[:16]}..., got {actual[:16]}...)"
        )
